### PR TITLE
[WIP] adding option to append 'stage' to function name

### PR DESCRIPTION
**Pull request by sepulworld**
In reference to: https://github.com/ubaniabalogun/serverless-package-python-functions/issues/12

### CODE REVIEW

**Comment by sepulworld** [comment]
Work in progress. Need to add an option to append 'stage' to function name

**Comment by sepulworld** [comment]
@ubaniabalogun I think we are good with this. Can you walk me through how to compile and run this locally? Sorry, I don't have local dev setup experience with serverless nodejs plugins

**Comment by ubaniabalogun** [comment]
@sepulworld 
Nice!
Local testing is pretty straight forward. Simply create a `.serverless_plugins` folder at the same level as the serverless.yml file of a serverless project, then clone the plugin repo into that folder.
I've got a demo serverless project that I use for testing which you can clone here https://github.com/ubaniabalogun/serverless-package-python-functions-demo

**Comment by sepulworld** [comment]
Thank you for the local development notes!

I tried but get an error not related to anything updated in this PR.

```
Serverless: [serverless-package-python-functions] Packaging set_office_hours...

  Type Error ---------------------------------------------

  _.concat is not a function

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: _.concat is not a function
    at PkgPyFuncs.makePackage (/Users/zane/src/oh-bot/.serverless_plugins/serverless-package-python-functions/index.js:158:20)
```

I wonder if by using this .serverless_plugins dir I need to pull in some dependencies into this folder as well?

**Comment by sepulworld** [comment]
Ah, looks like I had to install lodash

npm i --save lodash

**Comment by sepulworld** [comment]
After testing this out it doesn't deal with cloudwatch endpoint names and other things tied to the function name. 

I'm going to close this PR and instead suggest we update the README.md. I validated this method works great to deploy to multiple environments.

https://github.com/ubaniabalogun/serverless-package-python-functions/pull/15

**Pull request closed without merging**
